### ISSUE TITLE
Lacking Stone Tools

### ISSUE THREAD

**Issue by Slydragon05** [CorgiTaco/UnEarthed#7]
As the title may lead you to suggest, the lack of stone tools is causing some issues with modpacks involving this, I'm someone who's playing a modpack at current that involves this mod, the problem being that for whatever reason, the various stone types from this mod are not functioning as 'stone' for weapons/tools from base Minecraft, only from modded stone tools, is there any fix to this? Apologies for asking this but if you have a response, can you come to this Discord to speak to us about it (I'm not the modpack creator, just someone who helps find bugs and attempt to get some help from time to time. Thanks for your time and apologies for any inconvenience. 
https://discord.com/invite/yqjVqUV

**Comment by RDKRACZ** [comment]
Yes, please add tools for some if not all stone variants

**Comment by rafaelkai** [comment]
I second this, it makes getting stone almost impossible

**Comment by CorgiTaco** [comment]
Should be fixed in latest.
